apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookappfrontend
  labels:
    app: bookappfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookappfrontend
  template:
    metadata:
      labels:
        app: bookappfrontend
    spec:
      containers:
        - name: bookappfrontend
          image: pdelebarre/bookappfrontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
